mysql:
  enabled: false
  ip: "localhost:3306"
  database-name: vanish
  username: username1
  password: badpassword!
chat:
  prevent-direct-messages: true #only checks minecraft default commands
  fake-join-on-un-vanish: false
  fake-leave-on-vanish: false
  custom-message:
    enabled: false # The default provided by this plugin is a translatable minecraft message. It is recommended
    # you do not enable this unless you already modify your join/leave messages to be different from vanilla
    join: "<gray>[<green>+</green>]</gray> <displayname> <green>joined the game"
    leave: "<gray>[<dark_red>-</dark_red>]</gray> <displayname> <gray>left the game"
remove-from:
  tablist: true
  server-list: true
  required-sleeping-players: true
remind-while-vanished: true
remind-interval-in-seconds: 10
view:
  change-tablist: false
  glow-while-vanished: true
prevent-opening:
  - BARREL
  - CHEST
  - ENDER_CHEST
  - SHULKER_BOX

# Only enable if asked, will spam your console with random garbage
debug: false
