name: SimpleVanish
version: '${project.version}'
main: simplexity.simplevanish.SimpleVanish
api-version: '1.21.6'
softdepend:
  - PlaceholderAPI
permissions:
  vanish.view:
    default: op
    description: See other vanished people while they're vanished
    children:
      vanish.view.vanished: true
      vanish.view.tablist: true
      vanish.view.messages: true
  vanish.view.messages:
    default: op
    description: See messages when other people vanish or log in silently
  vanish.view.tablist:
    default: op
    description: See vanished members in the tab list
  vanish.view.vanished:
    default: op
    description: Vanished users are not hidden from you
  vanish.command:
    default: op
    description: use the /vanish command
    children:
      vanish.command.fake: true
  vanish.command.fake:
    default: op
    description: use the /fake leave and /fake join command
  vanish.settings:
    default: op
    description: Gives access to all admin features
    children:
      vanish.settings.core: true
      vanish.settings.interaction: true
      vanish.settings.admin: true
  vanish.settings.core:
    default: op
    description: Base permission for core vanish toggles
    children:
      vanish.settings.core.persist: true
      vanish.settings.core.spectator: true
      vanish.settings.core.night-vision: true
      vanish.settings.core.silent-join: true
      vanish.settings.core.silent-leave: true
  vanish.settings.core.persist:
    default: op
    description: Allows toggling whether vanish persists
  vanish.settings.core.spectator:
    default: op
    description: Gives access to spectator mode while vanished.
  vanish.settings.core.night-vision:
    default: op
    description: Gives the user night-vision while vanished
  vanish.settings.core.silent-join:
    default: op
    description: Allows you to join the server silently
  vanish.settings.core.silent-leave:
    default: op
    description: Allows you to leave the server silently
  vanish.settings.interaction:
    default: op
    description: Base permission for interaction toggles
    children:
      vanish.settings.interaction.break-blocks: true
      vanish.settings.interaction.open-containers: true
      vanish.settings.interaction.attack-entities: true
      vanish.settings.interaction.pick-up-items: true
      vanish.settings.interaction.mobs-target: true
  vanish.settings.interaction.break-blocks:
    default: op
    description: Allows toggling whether you can break blocks while vanished
  vanish.settings.interaction.open-containers:
    default: op
    description: Allows toggling whether you can open containers
  vanish.settings.interaction.attack-entities:
    default: op
    description: Allows toggling whether you can attack entities while vanished
  vanish.settings.interaction.pick-up-items:
    default: op
    description: Allows toggling whether you can pick up items while vanished
  vanish.settings.interaction.mobs-target:
    default: op
    description: Allows toggling whether mobs target while vanished
  vanish.settings.admin:
    default: op
    description: Base permission for admin toggles
    children:
      vanish.settings.admin.invulnerable: true
      vanish.settings.admin.flight: true
  vanish.settings.admin.invulnerable:
    default: op
    description: Allows toggling whether you are invulnerable while vanished
  vanish.settings.admin.flight:
    default: op
    description: Gives access to flight while vanished
  vanish.reload:
    default: op
    description: Reloads the plugin configuration and messages
commands:
  fake:
    permission: vanish.command.fake
    description: Allows a user to send a fake join or leave message
  vanish:
    permission: vanish.command
    description: Hides a player from other players
    aliases: [v, simplevanish, hide, sv]
  vanish-reload:
    permission: vanish.reload
    description: Reloads the plugin configuration and messages
    aliases: [vreload]
  vsettings:
    permission: vanish.command
    description: Command for adjusting personal settings for vanish
    aliases: [vsettings, vset, v-settings]
